# Generated by Django 5.0.3 on 2024-04-16 21:32

import django.db.models.deletion
from django.db import migrations, models


def create_roles(apps, schema_editor):
    Roles = apps.get_model('Account', 'role')
    datos = [
        {'role_descripction': 'Admin'},
        {'role_descripction': 'Ventas'},
        {'role_descripction': 'Soporte'},
        {'role_descripction': 'marketing'},
    ]
    for dato in datos:
        Roles.objects.create(**dato)


def create_models(apps, schema_editor):
    Modules = apps.get_model('Account', 'Module')
    datos = [
        {'description': 'ADMIN'},
        {'description': 'VENTAS'},
        {'description': 'SOPORTE'},
        {'description': 'MARKETING'},
    ]
    for dato in datos:
        Modules.objects.create(**dato)
class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Account",
            fields=[
                ("idcuenta", models.AutoField(primary_key=True, serialize=False)),
                ("first_name", models.CharField(max_length=50)),
                ("last_name", models.CharField(max_length=50)),
                ("id_card", models.CharField(max_length=10, unique=True)),
                ("last_login", models.DateTimeField(auto_now=True)),
                ("connected", models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name="Module",
            fields=[
                ("idModule", models.AutoField(primary_key=True, serialize=False)),
                ("description", models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name="role",
            fields=[
                ("idrole", models.AutoField(primary_key=True, serialize=False)),
                ("role_descripction", models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name="Permissions",
            fields=[
                (
                    "idPermissions",
                    models.IntegerField(primary_key=True, serialize=False),
                ),
                (
                    "Operation",
                    models.CharField(
                        choices=[("Modify", "Modify"), ("View", "View")], max_length=9
                    ),
                ),
                (
                    "idAccount",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="Account.account",
                    ),
                ),
                (
                    "idModule",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="Account.module"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Report",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("activity", models.CharField(max_length=45)),
                ("date", models.DateTimeField(auto_now=True)),
                (
                    "account_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="Account.account",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="account",
            name="role",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="Account.role"
            ),
        ),
        migrations.CreateModel(
            name="Credentials",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("email", models.CharField(max_length=150, unique=True)),
                ("password", models.CharField(max_length=150)),
                (
                    "idcuenta",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="Account.account",
                    ),
                ),
            ],
        ),migrations.RunPython(create_roles),
        migrations.RunPython(create_models),
    ]
