# Generated by Django 5.0.3 on 2024-03-30 15:47

import django.db.models.deletion
from django.db import migrations, models


def create_roles(apps, schema_editor):
    Roles = apps.get_model('Account', 'role')
    datos = [
        {'role': 'ADMIN'},
        {'role': 'SIN-ASIGNAR'},
    ]
    for dato in datos:
        Roles.objects.create(**dato)

class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="role",
            fields=[
                ("idrole", models.AutoField(primary_key=True, serialize=False)),
                ("role", models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name="Account",
            fields=[
                ("idcuenta", models.AutoField(primary_key=True, serialize=False)),
                ("first_name", models.CharField(max_length=50)),
                ("last_name", models.CharField(max_length=50)),
                ("cedula", models.CharField(max_length=10, unique=True)),
                ("last_login", models.DateTimeField(auto_now=True)),
                (
                    "role",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="Account.role"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Credentials",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("email", models.CharField(max_length=50, unique=True)),
                ("password", models.CharField(max_length=50)),
                (
                    "idcuenta",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="Account.account",
                    ),
                ),
            ],
        ), migrations.RunPython(create_roles)
    ]
