# Generated by Django 5.0.3 on 2024-03-30 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Account", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="credentials",
            name="email",
            field=models.CharField(max_length=150, unique=True),
        ),
        migrations.AlterField(
            model_name="credentials",
            name="password",
            field=models.CharField(max_length=150),
        ),
    ]
