# Generated by Django 5.0.3 on 2024-04-15 02:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("Account", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="account",
            old_name="cedula",
            new_name="id_card",
        ),
    ]
