# Generated by Django 5.0.3 on 2024-03-30 04:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Account", "0002_alter_account_password"),
    ]

    operations = [
        migrations.AlterField(
            model_name="account",
            name="role",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="Account.role"
            ),
        ),
    ]
