version: '3.8'
x-postgres-common:
  &postgres-common
  image: postgres:14-alpine
  user: postgres
  restart: always
  healthcheck:
    test: 'pg_isready -U ${POSTGRES_USER} --dbname=${POSTGRES_DB}'
    interval: 10s
    timeout: 5s
    retries: 5

services:
  db:
    <<: *postgres-common
    container_name: msadmin-users-db
    ports:
      - ${POSTGRES_PORT}:5432
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_HOST_AUTH_METHOD: "scram-sha-256\nhost replication all 0.0.0.0/0 md5"
      POSTGRES_INITDB_ARGS: "--auth-host=scram-sha-256"
    command: |
      postgres 
      -c wal_level=replica 
      -c hot_standby=on 
      -c max_wal_senders=10 
      -c max_replication_slots=10 
      -c hot_standby_feedback=on
    volumes:
      - db_volume_msadmin_users:/var/lib/postgresql/data
      - ./db/:/docker-entrypoint-initdb.d
    env_file:
      - .env

  db_replica:
    <<: *postgres-common
    container_name: msadmin-users-db-replica
    ports:
      - ${POSTGRES_PORT_REPLICA}:5432
    environment:
      PGUSER: replicator
      PGPASSWORD: replicator_password
    command: |
      bash -c "
      until pg_basebackup --pgdata=/var/lib/postgresql/data -R --slot=replication_slot --host=db --port=5432
      do
      echo 'Waiting for primary to connect...'
      sleep 1s
      done
      echo 'Backup done, starting replica...'
      chmod 0700 /var/lib/postgresql/data
      postgres
      "
    volumes:
      - db_replica_volume_msadmin_users:/var/lib/postgresql/data
    depends_on:
      - db
    env_file:
      - .env
    #rabbitmq:
    #  image: rabbitmq:3-management
    #  ports:
    #    - "5672:5672"  # Puerto para la comunicación AMQP
    #    - "15672:15672"  # Puerto para la interfaz de gestión web
    #  environment:
    #    RABBITMQ_DEFAULT_USER: usuario
    #    RABBITMQ_DEFAULT_PASS: adsadsdasasdasd


volumes:
  db_volume_msadmin_users:
  db_replica_volume_msadmin_users: