services:
  db:
    image: postgres:15.5
    container_name: msadmin_users_postgres_db
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      # Configuración para que escuche en la IP 127.0.0.1
      PGDATA: /var/lib/postgresql/data/pgdata
    ports:
      - "5432:5432" # Cambia la dirección IP aquí
    volumes:
      - db_volumes:/var/lib/postgresql/data/pgdata
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d ${POSTGRES_DB}"]
      interval: 10s
      timeout: 5s
      retries: 3

volumes:
  db_volume:
