# Generated by Django 5.0.3 on 2024-04-15 02:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("Account", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Module",
            fields=[
                ("idModule", models.AutoField(primary_key=True, serialize=False)),
                ("description", models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name="Permissions",
            fields=[
                (
                    "idPermissions",
                    models.IntegerField(primary_key=True, serialize=False),
                ),
                (
                    "Operation",
                    models.CharField(
                        choices=[
                            ("GET", "GET"),
                            ("POST", "POST"),
                            ("PUT", "PUT"),
                            ("DELETE", "DELETE"),
                        ],
                        max_length=9,
                    ),
                ),
                (
                    "idAccount",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="Account.account",
                    ),
                ),
                (
                    "idModule",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="Permissions.module",
                    ),
                ),
            ],
        ),
    ]
