# Generated by Django 5.0.3 on 2024-03-30 03:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Modulo",
            fields=[
                ("idModule", models.AutoField(primary_key=True, serialize=False)),
                ("description", models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name="Operation",
            fields=[
                ("idOperation", models.AutoField(primary_key=True, serialize=False)),
                ("description", models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name="Permissions",
            fields=[
                (
                    "idPermissions",
                    models.IntegerField(primary_key=True, serialize=False),
                ),
                (
                    "idAccount",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "idModule",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="Permissions.modulo",
                    ),
                ),
                (
                    "idOperation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="Permissions.operation",
                    ),
                ),
            ],
        ),
    ]
