# Generated by Django 5.0.3 on 2024-03-30 15:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Account", "0001_initial"),
        ("Permissions", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="permissions",
            name="idAccount",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="Account.account"
            ),
        ),
    ]
